# This file is settings to be merged into the pcluster-config.yaml file after the initial configuration.
HeadNode:
  LocalStorage:
    RootVolume:
      Encrypted: false
Scheduling:
  SlurmSettings:
    EnableMemoryBasedScheduling: true
    ScaledownIdletime: 30  # default is 10 minutes
    CustomSlurmSettings:
      - SlurmctldDebug: info  # default is "verbose"
      - Waittime: 30          # default is 0
      - MaxJobCount: 1000     # default is 10000
      - MaxStepCount: 4000    # default is 40000
      - MaxTasksPerNode: 32   # default is 512
      - PropagateResourceLimits: "NONE"  # default is "ALL"
      - AccountingStoreFlags: job_comment
      - PrologFlags: "contain"  # default is "none"
      - CompleteWait: 8       # default is 0, recommended somwhere between 0 and 32
      - DefMemPerCPU: 1280
      - MaxMemPerCPU: 1945
      - MpiDefault: pmi2 # default is none
  SlurmQueues:
    - Name: compute
      CapacityType: "SPOT"  # default is "ON_DEMAND"
      ComputeSettings:
        LocalStorage:
          EphemeralVolume:
            MountDir: /scratch
      CustomSlurmSettings:
        MaxNodes: 4
        MaxTime: "4:00:00"
      ComputeResources:
        - SchedulableMemory: 15600  # see: https://docs.aws.amazon.com/parallelcluster/latest/ug/slurm-mem-based-scheduling-v3.html#slurm-mem-based-scheduling-realmemory-v3
        # TODO: DisableSimultaneousMultithreading: true
