apiVersion: 1
datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s
  - name: cloudwatch
    type: cloudwatch
    editable: true
    jsonData:
      authType: default
      defaultRegion: us-east-1
