{
 "title": "Head Node Details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "id",
    "query": {
     "query": "label_values(node_uname_info{instance_name=~'HeadNode'}, instance_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance_id=~'$id'})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance_id=~'$id'})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{instance_id=~'$id', mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance_id=~'$id',mode='idle'}[10s])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance_id=~'$id'} / (node_memory_MemTotal_bytes{instance_id=~'$id'})))* 100",
     "legendFormat": "Used RAM"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance_id=~'$id',fstype=~'ext4|xfs',mountpoint!='/boot'}-node_filesystem_free_bytes{instance_id=~'$id',fstype=~'ext4|xfs',mountpoint!='/boot'}"
    },
    {
     "expr": "node_filesystem_free_bytes{instance_id=~'$id',fstype=~'ext4|xfs',mountpoint!='/boot'}-0",
     "legendFormat": "Available"
    },
    {
     "expr": "node_filesystem_size_bytes{instance_id=~'$id',fstype=~'ext4|xfs',mountpoint!='/boot'}-0"
    },
    {
     "expr": "node_filesystem_size_bytes{instance_id=~'$id',fstype=~'ext4|xfs',mountpoint!='/boot'}-0"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance_id=~'$id'} - node_memory_MemAvailable_bytes{instance_id=~'$id'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance_id=~'$id'}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance_id=~'$id'}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_load1{instance_id=~'$id'}", "legendFormat": "1m" },
    { "expr": "node_load5{instance_id=~'$id'}", "legendFormat": "5m" },
    {
     "expr": "node_load15{instance_id=~'$id'}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance_id=~'$id',mode='system'}[10s])) by (instance)",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance_id=~'$id',mode='user'}[10s])) by (instance)",
     "legendFormat": "User"
    },
    {
     "expr": "clamp_min((1 - avg(rate(node_cpu_seconds_total{instance_id=~'$id',mode='idle'}[10s])) by (instance)) - (avg(rate(node_cpu_seconds_total{instance_id=~'$id',mode='user'}[10s])) by (instance) + avg(rate(node_cpu_seconds_total{instance_id=~'$id',mode='system'}[10s])) by (instance)), 0)",
     "legendFormat": "Other"
    },
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{instance_id=~'$id',mode='idle'}[10s])) by (instance)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance_id=~'$id',fstype=~'ext4|xfs',mountpoint!='/boot'} - node_filesystem_free_bytes{instance_id=~'$id',fstype=~'ext4|xfs',mountpoint!='/boot'} ",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_context_switches_total{instance_id=~'$id'}[10s])",
     "legendFormat": "Context Switches"
    }
   ]
  },
  {
   "title": "Disk R/W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance_id=~'$id'}[20s])",
     "legendFormat": "{{device}} Read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance_id=~'$id'}[20s])",
     "legendFormat": "{{device}} Write"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance_id=~'$id',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[20s])*8",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance_id=~'$id',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[20s])*8",
     "legendFormat": "Transmit"
    }
   ]
  }
 ]
}