{
 "title": "Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "head_node_id",
    "query": {
     "query": "label_values(node_uname_info{instance_name=~'HeadNode'}, instance_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPUs Allocated",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slurm_cpus_total-slurm_cpus_idle",
     "legendFormat": "__auto"
    },
    { "expr": "slurm_cpus_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(slurm_account_mem_alloc) or vector(0)",
     "legendFormat": "__auto"
    },
    { "expr": "slurm_account_mem_real", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "/home Storage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance_id=\"$head_node_id\",mountpoint=\"/home\"}-node_filesystem_free_bytes{instance_id=\"$head_node_id\",mountpoint=\"/home\"}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance_id=\"$head_node_id\",mountpoint=\"/home\"}-0"
    }
   ]
  },
  {
   "title": "User Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(slurm_user_state_total{state=\"RUNNING\"}) by (username)",
     "legendFormat": "{{username}} running"
    },
    {
     "expr": "sum(slurm_user_state_total{state=\"CONFIGURING\"}) by (username)",
     "legendFormat": "{{username}} booting"
    },
    {
     "expr": "sum(slurm_user_state_total{state=\"PENDING\"}) by (username)",
     "legendFormat": "{{username}} pending"
    }
   ]
  },
  {
   "title": "Scheduler Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jobs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(slurm_account_job_state_total{state=\"COMPLETED\"})",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(slurm_account_job_state_total{state=\"COMPLETING\"})",
     "legendFormat": "Completing"
    },
    {
     "expr": "sum(slurm_account_job_state_total{state=\"RUNNING\"}) or vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(slurm_account_job_state_total{state=\"CONFIGURING\"})",
     "legendFormat": "Awaiting Node Boot"
    },
    {
     "expr": "sum(slurm_account_job_state_total{state=\"PENDING\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(slurm_account_job_state_total{state=\"SUSPENDED\"})",
     "legendFormat": "Suspended"
    },
    {
     "expr": "sum(slurm_account_job_state_total{state=~\"DEADLINE|FAILED|NODE_FAIL|BOOT_FAIL|OUT_OF_MEMORY|PREEMPTED|TIMEOUT|CANCELLED\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(slurm_account_job_state_total{state!~\"COMPLETED|COMPLETING|RUNNING|CONFIGURING|PENDING|SUSPENDED|DEADLINE|FAILED|NODE_FAIL|BOOT_FAIL|OUT_OF_MEMORY|PREEMPTED|TIMEOUT|CANCELLED\"})",
     "legendFormat": "Other"
    },
    {
     "expr": "sum(slurm_account_job_state_total) or vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(slurm_node_count_per_state{state=~\"(alloc|comp)[^~#%*+]*\"}) or vector(0)",
     "legendFormat": "Fully Used"
    },
    {
     "expr": "sum(slurm_node_count_per_state{state=~\"mix[^~#%*]*\"}) or vector(0)",
     "legendFormat": "Partially Used"
    },
    {
     "expr": "sum(slurm_node_count_per_state{state=~\"idle[^~#%*]*\"}) or vector(0)",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(slurm_node_count_per_state{state=~\"[a-z]+[*]|down|drain|drng|fail|failg|futr|maint|npc|resv|unk|maint|plnd\"})\n    ",
     "legendFormat": "Not Available"
    },
    {
     "expr": "sum(slurm_node_count_per_state{state=~\"[a-z]+[#]|pow_up\"})",
     "legendFormat": "Booting"
    },
    {
     "expr": "sum(slurm_node_count_per_state) or vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU, Memory & Disk Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total CPU cores",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{mode=\"idle\",instance_id!=\"$head_node_id\"})"
      }
     ]
    },
    {
     "title": "Avg. CPU cores",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{mode=\"idle\",instance_id!=\"$head_node_id\"})/count(count(node_cpu_seconds_total{instance_id!=\"$head_node_id\"}) by (instance_id))"
      }
     ]
    },
    {
     "title": "Total CPU use",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance_id!=\"$head_node_id\"}[1m]))"
      }
     ]
    },
    {
     "title": "Avg. CPU use",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance_id!=\"$head_node_id\"}[1m]))/count(count(node_cpu_seconds_total{instance_id!=\"$head_node_id\"}) by (instance_id))"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance_id!=\"$head_node_id\"})"
      }
     ]
    },
    {
     "title": "Avg. Memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance_id!=\"$head_node_id\"})/count(node_memory_MemTotal_bytes{instance_id!=\"$head_node_id\"})"
      }
     ]
    },
    {
     "title": "Total Memory use",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance_id!=\"$head_node_id\"}) - sum(node_memory_MemAvailable_bytes{instance_id!=\"$head_node_id\"})"
      }
     ]
    },
    {
     "title": "Avg. Memory use",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(sum(node_memory_MemTotal_bytes{instance_id!=\"$head_node_id\"}) - sum(node_memory_MemAvailable_bytes{instance_id!=\"$head_node_id\"}))/count(node_memory_MemTotal_bytes{instance_id!=\"$head_node_id\"})"
      }
     ]
    },
    {
     "title": "Total Disk (write)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total{instance_id!=\"$head_node_id\"}[1m]))"
      }
     ]
    },
    {
     "title": "Avg. Disk (write)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 18, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total{instance_id!=\"$head_node_id\"}[1m])) / count(node_disk_written_bytes_total{instance_id!=\"$head_node_id\"})"
      }
     ]
    },
    {
     "title": "Total Disk (read)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 20, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{instance_id!=\"$head_node_id\"}[1m]))"
      }
     ]
    },
    {
     "title": "Avg. Disk (read)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{instance_id!=\"$head_node_id\"}[1m])) / count(node_disk_read_bytes_total{instance_id!=\"$head_node_id\"})"
      }
     ]
    },
    {
     "title": "CPU load",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{mode=\"idle\",instance_id!=\"$head_node_id\"})",
       "legendFormat": "Total cores"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance_id!=\"$head_node_id\"}[1m]))",
       "legendFormat": "Load in cores"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance_id!=\"$head_node_id\"})",
       "legendFormat": "Total Memory"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance_id!=\"$head_node_id\"}) - sum(node_memory_MemAvailable_bytes{instance_id!=\"$head_node_id\"})",
       "legendFormat": "Used Memory"
      }
     ]
    },
    {
     "title": "Disk I/O (read)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{instance_id!=\"$head_node_id\"}[1m]))",
       "legendFormat": "Read throughput"
      }
     ]
    },
    {
     "title": "Disk I/O (write)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total{instance_id!=\"$head_node_id\"}[1m]))",
       "legendFormat": "Write throughput"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current Total Throughput (Transmit)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',instance_id!=\"$head_node_id\"}[1m]))"
      }
     ]
    },
    {
     "title": "Current Avg. Throughput per Node (Transmit)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',instance_id!=\"$head_node_id\"}[1m]))/count(count(node_network_transmit_bytes_total{instance_id!=\"$head_node_id\"}) by(instance_id))"
      }
     ]
    },
    {
     "title": "Current Total Throughput (Receive)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',instance_id!=\"$head_node_id\"}[1m]))"
      }
     ]
    },
    {
     "title": "Current Avg. Throughput per Node (Receive)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',instance_id!=\"$head_node_id\"}[1m]))/count(count(node_network_receive_bytes_total{instance_id!=\"$head_node_id\"}) by(instance_id))"
      }
     ]
    },
    {
     "title": "Throughput (Transmit)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',instance_id!=\"$head_node_id\"}[1m]))",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "Throughput (Receive)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*',instance_id!=\"$head_node_id\"}[1m]))",
       "legendFormat": "Receive"
      }
     ]
    }
   ]
  }
 ]
}